/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.6/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application

}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

tasks.withType<Test> {
    this.testLogging {
        this.showStandardStreams = true
    }
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)
	// testImplementation("org.json:json:20240303")
 //    testImplementation("io.vavr:vavr:0.10.0")

    // This dependency is used by the application.
    // implementation(libs.guava)
	implementation("org.json:json:20240303")
    implementation("io.vavr:vavr:0.10.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "main.Main"
}
